sonar.projectKey=thibautlfr-studylab_oc-p10-ci-cd
sonar.organization=thibautlfr-studylab
sonar.projectName=oc-p10-ci-cd

# Paths to source directories
sonar.sources=back/src/main/java,front/src/app

# Paths to test directories
sonar.tests=back/src/test/java,front/src/app
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java
sonar.exclusions=**/node_modules/**,**/target/**,front/src/test.ts,front/src/polyfills.ts,front/src/environments/**

# Java specific
sonar.java.binaries=back/target/classes
sonar.java.libraries=back/target/dependency/*.jar
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# TypeScript/JavaScript specific
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
